class Config
  @client: Langchain::LLM::OpenAI
  @role: String
  @prompt: String

  def self.configure: { (Config) -> void } -> Config

  attr_accessor client: Langchain::LLM::OpenAI
  attr_accessor role: String
  attr_accessor prompt: String
end