class Config
  def self.configure: () { (*Block) -> Config } -> Config

  public

  def client: () -> Langchain::LLM::OpenAI

  def client=: (Langchain::LLM::OpenAI) -> void

  def prompt: () -> String

  def prompt=: (String) -> void

  def role: () -> String

  def role=: (String) -> void
end