class Runner
  @config: Config

  def initialize: (config: Config) -> void
    @config = config
  end

  def run: () -> OpenAI::ChatCompletion
    config.client.chat(messages: [{ role: config.role, content: config.prompt}]).chat_completion
  end

  private

  attr_reader config: Config
end